import Head from "next/head";
import React from "react";
import { NavBar } from "./index";

function About() {
  return ( <>
    <Head>
      <title>Home - Digital~Infamy</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <nav className="sticky" style={{ zIndex: 1000 }}>
      <div className="nav-container p-8">
        <NavBar />
      </div>
    </nav>
    <main className="content">
      <h1>About Us</h1>
    </main>
  </> );
}

export default About;