import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { FaCss3Alt, FaHtml5, FaNodeJs } from "react-icons/fa";
import { FcMenu } from "react-icons/fc";
import { RiReactjsLine } from "react-icons/ri";
import { SiJavascript, SiTypescript } from "react-icons/si";
import { Events, Link, scrollSpy } from "react-scroll";
import useMobileDetect from "../components/device/useMobileDetect";
import ScrollToTop from "../components/scroll-to-top/ScrollToTop";

function NavBar() {
  const { isMobile } = useMobileDetect();

  const getOffset = (): number => !isMobile() ? -200 : -60;
  useEffect(() => {
    scrollSpy.update();
  }, []);
  return ( <ul className="navbar-nav">
    <li><Link activeClass="active" href="#home" to="home" spy={true} smooth={true} duration={1500}
              offset={getOffset()}>Home</Link></li>
    <li><Link activeClass="active" href="#about" to="about" spy={true} smooth={true} duration={1500}
              offset={getOffset()}>About</Link></li>
    <li><Link activeClass="active" href="#skills" to="skills" spy={true} smooth={true} duration={1500}
              offset={getOffset()}>Skills</Link></li>
    <li><Link activeClass="active" href="#projects" to="projects" spy={true} smooth={true} duration={1500}
              offset={getOffset()}>Projects</Link></li>
  </ul> );
}


const Home: NextPage = () => {
  const { isMobile } = useMobileDetect();
  const [menuOpen, setMenuOpen] = useState(isMobile());
  useEffect(() => {
    Events.scrollEvent.register('start', function() {
      setMenuOpen(false);
    });
    Events.scrollEvent.register('end', function() {
      setMenuOpen(false);
    });
  }, [])

  return (
    <>
      <Head>
        <title>Home - Digital~Infamy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="sticky">
        <div className="nav-container container">
          <div className="nav-header-container">
            {isMobile() ?
              <div>
                <button className="navbar-toggler text-4xl"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarCollapse"
                        aria-controls="navbarCollapse"
                        aria-expanded={menuOpen}
                        aria-label="Toggle navigation"
                        onClick={() => setMenuOpen(!menuOpen)}
                >
                  <div id={`nav-icon1`} className={menuOpen ? 'open': ''}>
                    <span></span>
                    <span></span>
                    <span></span>
                  </div>
                </button>
              </div> : null}
            <div className="nav-logo-container">
              <h1 className="font-extralight">Digital Infamy</h1>
            </div>
          </div>
          {isMobile() ?
            <div className="mobileMenu">
              {menuOpen ? <NavBar /> : null}
            </div> : <div className="deskTopMenu">
              <NavBar />
            </div>
          }
        </div>
      </nav>
      <main className="content">
        <section id="home" className="home container m-auto p-8">
          <div className="header-container">
            <h2 className="text-center">Hey, I&apos;m Andrew Allison</h2>
          </div>
          <p className="text-center text-4xl p-6">A Software developer with over 15 years of experience.</p>
          <p className="text-center text-3xl text-gray-300">I enjoy building things and solving problems with
            technology.</p>
        </section>
        <section id="about" className="about container m-auto p-8 text-center">
          <div className="text-center header-container">
            <h2 className="text-6xl">About</h2>
          </div>
          <p className="text-center p-4">I have worked in the tech industry for over 15 years. Working in various sized
            companies from large multi-nationals such as Northgate Arinso to early stage start-ups such as Fundify and
            TalkBe </p>
          <p className="text-center p-4">
            I have worked mostly as a software developer writing code, working with project managers to help deliver
            projects as well as helping to mentor junior members of staff.
            I have also been in roles that have involved me stepping away from coding and running digital transformation
            projects such as Billing Platform implementations.
          </p>
        </section>
        <section id="skills" className="skills container m-auto p-8">
          <div className="header-container">
            <h2 className="text-center text-6xl">Skills</h2>
          </div>
          <p className="text-center p-4">Some of the most recent Technologies and buzz-wordy things I&apos;ve been
            working on and with. </p>
          <h3 className="text-center text-4xl">Languages</h3>
          <div className="coding-skills">
            <div className="text-center skill-item">
              <FaHtml5 className="text-8xl" />
              <h4>Html</h4>
            </div>
            <div className="text-center skill-item">
              <FaCss3Alt className="text-8xl" />
              <h4>CSS</h4>
            </div>
            <div className="text-center skill-item">
              <SiTypescript className="text-8xl" />
              <h4>Typescript</h4>
            </div>
            <div className="text-center skill-item">
              <SiJavascript className="text-8xl" />
              <h4>Javascript</h4>
            </div>
          </div>
          <h3 className="text-center text-4xl">Frameworks</h3>
          <div className="coding-skills">
            <div className="text-center skill-item">
              <RiReactjsLine className="text-8xl" />
              <h4>React</h4>
            </div>
            <div className="text-center skill-item">
              <FaNodeJs className="text-8xl" />
              <h4>NodeJs</h4>
            </div>
          </div>
        </section>
        <section id="projects" className="projects container m-auto p-8">
          <div className="header-container">
            <h2 className="text-center text-6xl">Projects</h2>
          </div>
          <h3 className="text-4xl text-center m-4">COMING SOON</h3>
          <p className="text-center">I&apos;m looking to add a load of info here about which projects I&apos;m working
            on.</p>
        </section>
      </main>
      <ScrollToTop key={`scroll-to-top`} />
    </>
  );
};

export default Home;